version: 2.1
jobs:
 build:
   docker:
     - image: circleci/node:10
   steps:
     - checkout
     - run:
         name: Run tests
         command: |
           yarn add tap-xunit
           mkdir -p ~/reports
           yarn run test --tap | ./node_modules/tap-xunit/bin/tap-xunit > ~/reports/ava.xml
         when: always
     - store_test_results:
         path: ~/reports
     - store_artifacts:
         path: ~/reports          

